apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finsentinel.fullname" . }}-api-config
  labels:
    app.kubernetes.io/name: finsentinel
    app.kubernetes.io/component: api
data:
{{- range $key, $value := .Values.api.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
