{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finsentinel.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: finsentinel
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
{{- end }}
