apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finsentinel.fullname" . }}-web
  labels:
    app.kubernetes.io/name: finsentinel
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: finsentinel
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: finsentinel
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "finsentinel.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
{{ toYaml .Values.web.resources | indent 12 }}
