apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finsentinel.fullname" . }}-web

spec:
  replicas: {{ .Values.web.replicas }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: finsentinel-web

  template:
    metadata:
      labels:
        app: finsentinel-web

    spec:
      serviceAccountName: {{ include "finsentinel.serviceAccount" . }}

      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 3000

          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          resources:
{{ toYaml .Values.web.resources | indent 12 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finsentinel.fullname" . }}-web

spec:
  type: {{ .Values.web.service.type }}

  selector:
    app: finsentinel-web

  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http

      {{- if eq .Values.web.service.type "NodePort" }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
