apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finsentinel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Rajan-Upadhyay21/finsentinel-ai.git
    targetRevision: main
    path: infrastructure/helm/finsentinel
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: finsentinel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
