global:
  imagePullSecrets: []

serviceAccount:
  create: true

api:
  replicaCount: 1
  image:
    repository: finsentinel-api
    tag: day9
    pullPolicy: Never
  existingSecret: ""
  service:
    type: NodePort
    port: 8000
    nodePort: 30080
  config:
    APP_ENV: development
    OTEL_TRACING_ENABLED: "false"
  probes:
    startupPath: /health/live
    livenessPath: /health/live
    readinessPath: /health/live
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

web:
  replicaCount: 1
  image:
    repository: finsentinel-web
    tag: day9
    pullPolicy: Never
  service:
    type: NodePort
    port: 3000
    nodePort: 30081
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilization: 70

pdb:
  enabled: false
  minAvailable: 1

networkPolicy:
  enabled: false
